spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: business-transaction-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.18:8848
    sentinel:
      transport:
        dashboard: 192.168.10.18:8858
dubbo:
  scan:
    base-packages: com.fun.uncle.hello.seata.business.controller
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://192.168.10.18:8848
server:
  port: 12001
management:
  endpoints:
    web:
      exposure:
        include: "*"