spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: hello-seata-provider-order-item
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.18:8848
    alibaba:
      seata:
        # 自定义事务组名称 tx_group，需要与服务端一致
        tx-service-group: tx-group
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 这里使用的是 ip:13307/db_order_item 的数据库（一个服务一个数据库）
    jdbc-url: jdbc:mysql://192.168.10.31:13307/db_order_item?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
dubbo:
  scan:
    base-packages: com.fun.uncle.hello.seata.provider.service
  protocol:
    name: dubbo
    port: -1
  provider:
    loadbalance: roundrobin
  registry:
    address: nacos://192.168.10.18:8848
mybatis:
  type-aliases-package: com.fun.uncle.hello.seata.provider.domain
  mapper-locations: classpath:mapper/*.xml
#logging:
#  level:
#    com.fun.uncle.hello.seata.provider.mapper: debug
#    io.seata.core: debug